config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  authenticated :user do
    root to: "posts#index"
  end
  devise_scope :user do
    root to: "users/sessions#new", as: "login_root"
  end

  get 'likes/:post_id', to: "posts#likes", as: 'likes'

  get 'profiles/:id', to: 'profiles#show', as: 'profiles'
  get 'profiles/:id/all', to: 'profiles#index', as: 'find_friends'
  get 'profiles/:id/friends', to: 'profiles#friends', as: 'friends'
  get 'profiles/:id/requests', to: 'profiles#requests', as: 'requests'
  get 'profiles/:id/posts', to: 'profiles#posts', as: 'user_posts'
  get 'profiles/:friend_id/add', to: 'profiles#add', as: 'add_profile'
  get 'add/:friend_id', to: "friends#add", as: 'add'

  get 'cancel/:friend_id', to: "friends#cancel", as: 'cancel'
  get 'ignore/:friend_id', to: "friends#ignore", as: 'ignore'
  get 'remove/:friend_id', to: "friends#remove", as: 'remove'
  get 'accept/:friend_id', to: "friends#accept", as: 'accept'

  post '/notify', to: "friends#notify", as: 'notify'

  resources :posts
  resources :comments
  resources :likes
  resources :friends
end

app/controllers/profiles_controller.rb
# frozen_string_literal: true

class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:add]
  def show
    @user = User.find(params[:id])
    @sender = Friend.where('receiver_id = ? AND sender_id = ?', @user.id, current_user.id).first
    @receiver = Friend.where('receiver_id = ? AND sender_id = ?', current_user.id, @user.id).first
    @posts = Post.where('user_id IN(?)', @user.id).order(created_at: 'DESC')
    @comment = Comment.new
    @post = Post.new
  end

  def posts
    @user = User.find(params[:id])
    @posts = Post.where('user_id IN(?)', @user.id).order(created_at: 'DESC')
    @comment = Comment.new
    @post = Post.new
  end

  def friends
    @user = User.find(params[:id])
    @ids = create_friends_ids(params[:id])
    @friends = User.where('id IN (?)', @ids)
  end

  def requests
    @user = User.find(params[:id])
    @user_ids = Friend.select(:sender_id).where('receiver_id = ? AND confirmed = false', current_user.id)
    @requests = User.where('id in(?)', @user_ids)
  end

  def create_friends_ids(id)
    @friends_id = Friend.select(:sender_id).where('(receiver_id = ?) AND confirmed = true', id)
    @friends_id2 = Friend.select(:receiver_id).where('(sender_id = ?) AND confirmed = true', id)
    set_ids(@friends_id, @friends_id2)
  end

  def set_ids(friends_id, friends_id2)
    ids = []
    friends_id.each do |key|
      ids << key[:sender_id]
    end
    friends_id2.each do |key|
      ids << key[:receiver_id]
    end
    ids
  end

  def add
    @sender = Friend.where('receiver_id = ? AND sender_id = ?', @user.id, current_user.id).first
    @receiver = Friend.where('receiver_id = ? AND sender_id = ?', @current_user.id, @user.id).first
    return unless @sender.nil? || @receiver.nil?

    Friend.create(sender_id: @current_user.id, receiver_id: params[:friend_id], confirmed: false)
    @sender = Friend.where('receiver_id = ? AND sender_id = ?', @user.id, @current_user.id).first
    @receiver = Friend.where('receiver_id = ? AND sender_id = ?', @current_user.id, @user.id).first
  end

  def index
    @friends_id3 = Friend.select(:sender_id).where('(receiver_id = ?) AND confirmed = true', current_user.id)
    @friends_id4 = Friend.select(:receiver_id).where('(sender_id = ?) AND confirmed = true', current_user.id)
    @ids2 = set_ids(@friends_id3, @friends_id4)
    @ids2 << current_user.id
    @not_friends = User.where('id NOT IN (?)', @ids2)
    @not_friends = User.all if @not_friends.empty?
  end

  def set_user
    @user = User.find(params[:friend_id])
  end
end

app/helpers/profiles_helper.rb
# frozen_string_literal: true

module ProfilesHelper
end

app/views/profiles/_friends.html.erb
<section class="all-friends">
  <% @friends.each do |friend| %>
    <div class="friend-div">
    <h3 class="friends-font"> <%= link_to "#{friend.name.capitalize}", profiles_path(friend.id) %> </h3>
    <div class="gravatar-container"> <%= gravatar_for friend %> </div>
    <% if current_user.id == @user.id %>
    <h3 class="friends-font"> <%= link_to "Remove", ignore_path(friend.id) %> </h3>
    <% end %>
    </div>
  <% end %>
</section>

app/views/profiles/_main_profile_links.html.erb
<% if current_user.id == @user.id%>

<% elsif @sender.nil? && @receiver.nil?%>
    <%= link_to "Add friend", add_path(@user.id), class: "accept", remote: true%>
<% elsif !@sender.nil? && !@sender.confirmed && current_user.id = @sender.id %>
  <%= link_to "Cancel request", cancel_path(@user.id), class: "ignore" %>
<% elsif @receiver.nil? && @sender.confirmed || @receiver.confirmed %>
  <%= link_to "Remove friend", remove_path(@user.id), class: "ignore" %>
<% elsif !@receiver.nil? %>
<%= link_to "Accept friend", accept_path(@user.id), class: "accept" %>
<%= link_to "Ignore friend", ignore_path(@user.id), class: "ignore" %>
<% end %>

app/views/profiles/_new_friends.html.erb
  <div class="body">
    <main class="all-users">
      <article class ="all-friends">
        <% @not_friends.each do |user| %>
          <div class="friend-div">
          <h3 class="users-font"> <%= link_to "#{user.name.capitalize}", profiles_path(user.id) %> </h3>
          <div class="gravatar-container"> <%= gravatar_for user %> </div>
          </div>
        <% end %>
      </article>
    </main>
  </div>

app/views/profiles/_posts.html.erb
<div class="post-container">
  <% if @user.nil? || @user.id == current_user.id %>
    <%= form_for(@post) do |f|%>
      <%= f.text_area :content, class: "post", placeholder: "Tell us!" %>
        <% if @post.errors.any? %>
          <ul class="error-content">
            <% @post.errors.full_messages.each do |msg|%>
              <li><%= msg %></li>
            <% end %>
          </ul>
        <% end %>
      <%= f.submit "Post", class: "post-button"%>
    <% end %>
  <% end %>
  <% @posts.each do |post|%>
    <div id="render-post-<%= post.id %>"class="posted">
        <br>
        <span><%= link_to "#{post.user.name}", profiles_path(post.user.id), class: "link_profile"%>
          <%= "shared a post. " %>
          <span class="time-post"><%= time_ago_in_words(post.created_at) %> ago.</span></span>
        <div class="p-post"> <%= simple_format(post.content) %> </div>
        <div>
          <%= link_to tag.i(class: "glyphicon glyphicon-thumbs-up"), likes_path(post.id), name: "like", remote: true %>
          <span id="render-likes-<%= post.id %>"><%= post.likes_count %></span>
        </div>
         <% if flash.any? %>
              <% flash.each do |type,obj| %>
                <% if type == "comment_errors" && post.id == obj[1]%>
                <ul class="error-content">
                  <li><%= obj[0][0] %></li>
                </ul>
                <% end %>
              <% end %>
          <% end %>
        <% post.comments.each do |comment| %>
          <div class="comments">
            <span><%= link_to comment.user.name, profiles_path(comment.user.id), class: "link_profile" %>
              <%= simple_format(comment.content) %></span>
          </div>
        <% end %>
        <br>
        <%= form_for(@comment, remote: true) do |f| %>
          <%= f.text_area :content, class: "comment", placeholder: "Comment your friend's post" %>
          <%= f.hidden_field :post_id, value: post.id %>
          <%= f.submit "Comment", class: "comment-button" %>
        <% end %>
      </div>
  <% end %>
</div>

app/views/profiles/_requests.html.erb
<section class="requests-container">
  <% if current_user.id == @user.id && @requests.any? %>
    <%= flash[:warning] %>
    <% @requests.each do |request| %>
      <span class="gravatar-container"> <%= gravatar_for(request,"gravatar-smaller") %> </span>
      <h3 class="friends-font"> <%= link_to "#{request.name.capitalize}", profiles_path(request.id) %> </h3>
      <%= link_to "Accept", accept_path(request.id), class: "accept margin-left" %>
      <%= link_to "Ignore", ignore_path(request.id), class: "ignore" %>
      <br> <br>
    <% end %>
  <% end %>
</section>

app/views/profiles/add.js.erb
$("#render-friend-request").html("<%= j render 'main_profile_links'%>")

app/views/profiles/friends.js.erb
$('#partial-render').html("<%= j render 'friends' %>")

app/views/profiles/index.js.erb
$('#partial-render').html("<%= j render 'new_friends' %>")

app/views/profiles/posts.js.erb
$('#partial-render').html("<%= j render 'posts' %>")

app/views/profiles/requests.js.erb
$('#partial-render').html("<%= j render 'requests' %>")

app/views/profiles/show.html.erb
<div class ="body">
  <div class = "post-container">
      <article>
        <div class="gravatar-wrapper">
          <%= image_tag("backprofile.jpg", class: "img-profile") %>
          <section class ="name-gravitar">
            <div friend-div>
              <%= gravatar_for @user %>
              <h1 class ="h1"> <%= @user.name.capitalize %> </h1>
            </div>
          </section>
          <section id="render-friend-request">
            <% if current_user.id == @user.id%>

            <% elsif @sender.nil? && @receiver.nil?%>
                <%= link_to "Add friend", add_profile_path(@user.id), class: "accept", remote: true %>
            <% elsif !@sender.nil? && !@sender.confirmed %>
              <%= link_to "Cancel request", cancel_path(@user.id), class: "ignore" %>
            <% elsif @receiver.nil? && @sender.confirmed || @receiver.confirmed %>
              <%= link_to "Remove friend", remove_path(@user.id), class: "ignore" %>
            <% elsif !@receiver.nil? %>
            <%= link_to "Accept friend", accept_path(@user.id), class: "accept" %>
            <%= link_to "Ignore friend", ignore_path(@user.id), class: "ignore" %>
            <% end %>
          </section>
        </div>
      </article>
      <nav class="normal-resolution">
        <ul class="nav-profile">
          <%= link_to "<li><span class='glyphicon glyphicon-list'></span> <div>Posts</div></li>".html_safe, user_posts_path(params[:id]), remote: true %>
          <%= link_to "<li><span class='glyphicon glyphicon-user'></span> <div>Friends</div></li>".html_safe, friends_path(params[:id]), remote: true %>
          <% if current_user.id == @user.id %>
            <%= link_to "<li><span class='glyphicon glyphicon-user first-glyphicon'><span class='glyphicon glyphicon-plus second-glyphicon'></span></span> <div>New friends</div></li>".html_safe, find_friends_path(current_user.id), remote: true %>
            <%= link_to "<li><span class='glyphicon glyphicon-user first-glyphicon'><span class='glyphicon glyphicon-th-list second-glyphicon'></span></span> <div>Friend requests <span id='notification_count3'></span></div></li>".html_safe, requests_path(current_user.id), remote: true %>
          <% end %>
        </ul>
      </nav>

      <nav class="small-resolution">
        <ul class="nav-profile">
          <%= link_to "<li><span class='glyphicon glyphicon-list'></span></li>".html_safe, user_posts_path(params[:id]), remote: true %>
          <%= link_to "<li><span class='glyphicon glyphicon-user'></span></li>".html_safe, friends_path(params[:id]), remote: true %>
          <% if current_user.id == @user.id %>
            <%= link_to "<li><span class='glyphicon glyphicon-user first-glyphicon'><span class='glyphicon glyphicon-plus second-glyphicon'></span></span> </li>".html_safe, find_friends_path(current_user.id), remote: true %>
            <%= link_to "<li><span class='glyphicon glyphicon-user first-glyphicon'><span class='glyphicon glyphicon-th-list second-glyphicon'></span><span id='notification_count4'></span></span></li>".html_safe, requests_path(current_user.id), remote: true %>
          <% end %>
        </ul>
      </nav>
      <div id="partial-render">
        <%= render 'posts' %>
      </div>
</div>